###
POST http://localhost:9000/api/citas HTTP/1.1
Content-Type: application/json

{
    "fecha": "29/05/2022",
    "hora": "09:00",
    "duracion": "20",
    "nombre": "Alex",
    "apellido1": "Lotas",
    "apellido2": "Gordas",
    "servicios": ["6273e8135619440a6adc49f9"],
    "tel1": "654823447",
    "tel2": "934863811" 
}

###

POST http://localhost:9000/api/events HTTP/1.1
Content-Type: application/json

{
    "start": "2022-06-01T08:00",
    "end": "2022-06-01T09:00",
    "title": "20"   
}

###
GET http://localhost:9000/api/citas HTTP/1.1

###
GET http://localhost:9000/api/citas/6275014a923aec70cb82cda9 HTTP/1.1

###
PUT http://localhost:9000/api/citas/6275014a923aec70cb82cda9 HTTP/1.1
Content-Type: application/json

{
    "fecha": "01/05/2022",
    "hora": "09:00",
    "duracion": "30",
    "nombre": "Manuel",
    "apellido1": "Lotas",
    "apellido2": "Gordas",
    "servicios": ["6273e8135619440a6adc49f9"],
    "tel1": "654823447",
    "tel2": "934863811" 
}

###
DELETE http://localhost:9000/api/citas/6275014a923aec70cb82cda9 HTTP/1.1

