###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "alex@gmail.com",
    "password": "123456",
    "nombre": "Felipe",
    "apellido1": "Lotas",
    "apellido2": "Gordas",
    "nacimiento": "28/03/1981",
    "tel1": "654823447",
    "tel2": "934863811",
    "genero": "Mujer",
    "role": "basic",
    "accessToken": ""
}

###

POST http://localhost:9000/api/signup HTTP/1.1
Content-Type: application/json

{
    "email": "alex@gmail.com",
    "password": "metallica9",
    "nombre": "Felipe",
    "apellido1": "Lotas",
    "apellido2": "Gordas",
    "nacimiento": "28/03/1981",
    "tel1": "654823447",
    "tel2": "934863811",
    "genero": "Mujer",
    "role": "basic",
    "accessToken": ""
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/627266ff8533e6469723289a HTTP/1.1

###
PUT http://localhost:9000/api/users/627266ff8533e6469723289a HTTP/1.1
Content-Type: application/json

{
    "name": "Maria del Mar",
    "age": "41",
    "email": "maria@gmail.com"
}

###
DELETE http://localhost:9000/api/users/6273e530cb1a3691cf04bb93 HTTP/1.1

